version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      qa-tooling:
        patterns:
          - "@axe-core/*"
          - "puppeteer"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
